= The Single Page Of REST
Ivan Osipov <contact@i-osipov.ru>
v0.2, September 19, 2020

:sectlinks:
:sectnumlevels: 1

image::https://www.repostatus.org/badges/latest/wip.svg[]

Use this document as a set of recommendations to build strong, predictable, easy to use REST APIs.
In general, REST is not only about API but about constraints for flexible and scalable applications (please, https://en.wikipedia.org/wiki/Representational_state_transfer[read Wikipedia^] for more information).
This document is mostly about **Uniform interface constraint**.

TIP: If you can remember only one thing: _DO API DESIGN UNIFORMLY EVERYWHERE_.

All recommendations follow the format:

== <number>. Name of a recommendation

=== Explanation

Detailed explanation of the recommendation

=== Alternatives (if applicable)

Only relevant alternatives

=== Reason

Why the recommendation is better than alternatives

:sectnums:

== Specify minimal Agreement for your clients

=== Explanation

Provide short agreement for your clients at least.
Specify how you are going to update API, what is its maximal transition period to migrate from a version N to version N+1 and similar generic information about the API.

=== Reason

If you are going to add fields to content of your API without version upgrade specify that in the agreement.
Your clients must know that they should not create their custom fields in DTO (Data Transfer Objects) on their side because of the contract.

If you have 1 year migration period from verison N to version N+1 specify that.
If you have marker metadata about API deprecation (for example, deprecation warning header) specify that.

== Create JSON-first API

=== Explanation

If a client doesn't provide Accept header specifying expected data format then return JSON.

=== Reason

Nowadays, JSON is a default format to transfer data.
It is simple, pretty concise, readable both by machines and humans.

== Use predictable and extendable base url

=== Explanation

* Use `rest.your-backend-domain.com` for external clients
* Use `your-frontend-domain.com/rest` for frontends

=== Alternatives

a. `api.your-backend-domain.com`
b. `your-backend-domain.com`
c. `rest.your-frontend-domain.com`

=== Reason

Use `rest` not `api` and not `zero` prefix because of extendability.
In one year you can provide extra GraphQL API for effective and flexible data fetching or any other API over http.
Two base urls `api.yourdbackendomain.com` (a) and `graphql.yourdbackendomain.com` will confuse your clients. Using root domain without subdomains (b)
will bring us to the previous issue again. Using subdomain for frontends can increase the complexity of API usage on the frontend side. In the case of `your-frontend-domain.com/rest`
A frontend team can just rely on relative paths.

== Make versioning mandatory

=== Explanation

The first thing to do if you create a new endpoint is to set a version.

=== Reason

If you don't have versioning for your API you either break backward compatibility or confuse your clients with version 2 when you didn't have version 1.

== Make simple and obvious versioning

=== Explanation

It is crucial for your clients easily understand API version. It makes strong expectations about responses and possibility to upgrade.

The option with relatively minimal set of disadvantages is versioning in URL: `rest.your-domain.com/v3/articles`.
Scope of versioning should cover as much as possible otherwise it can bring your clients to a misunderstanding of reasons why you limited scope for a particular sub-URL,
redundant complexity, paying too much attention to version position in URL.

=== Alternative

a. Version as a custom header `X-API-VERSION`
b. Version as a part of Accept header
c. Version as a query parameter

=== Reason

Advantages:

- the simplest, and the most obvious way to do versioning
- impossible to ignore version
- obvious scope of versioning (the following part of URL)
- if API is public it is enough to have any browser to test endpoint

Disadvantages:

- In some web frameworks to follow that approach it will require to create new files/classes to handle requests with next version

The alternatives either over-complicated for clients or not obvious.
In some cases, clients have to know the proper header (a) or its format can be difficult to read (b).
Versioning using query param list (c) is simpler than versioning using header, but it still doesn't have an obvious scope and there is a possibility to ignore the parameter until you see an error from the server. It can be missed among other parameters as well, so it is harder to work with.

== Nouns-first design

== Design Predictable API

== Provide extendable response

== Sensible HTTP verbs

== Provide partial response

== Show deprecation warnings

== Allow pagination

== Format errors

== Avoid composite id, no deep embedding

== Use HTTP content negotiation

== Use standard HTTP cache

== Case of fields should depend on most of your clients

== Design Batch Requests

== Provide useful flags if a client can need it

== Provide time only in UTC+0